medical_back/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');


Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');

Route::resource('countryNames', 'country_nameController');

Route::resource('countryUniversities', 'country_universitiesController');

Route::resource('universityInfos', 'university_infoController');

Route::resource('universityImages', 'university_imagesController');

Route::resource('banners', 'bannerController');

Route::resource('logos', 'logoController');













Route::resource('abouts', 'aboutController');

medical_back/app/Models/university_info.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * @SWG\Definition(
 *      definition="university_info",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="university_id",
 *          description="university_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="university_info",
 *          description="university_info",
 *          type="string"
 *      )
 * )
 */
class university_info extends Model
{

    public $table = 'university_info';
    



    public $fillable = [
        'university_id',
        'university_info'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'university_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

medical_back/app/Http/Controllers/university_infoController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\university_infoDataTable;
use App\Http\Requests;
use App\Models\country_universities;
use App\Http\Requests\Createuniversity_infoRequest;
use App\Http\Requests\Updateuniversity_infoRequest;
use App\Repositories\university_infoRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class university_infoController extends AppBaseController
{
    /** @var  university_infoRepository */
    private $universityInfoRepository;

    public function __construct(university_infoRepository $universityInfoRepo)
    {
        $this->universityInfoRepository = $universityInfoRepo;
    }

    /**
     * Display a listing of the university_info.
     *
     * @param university_infoDataTable $universityInfoDataTable
     * @return Response
     */
    public function index(university_infoDataTable $universityInfoDataTable)
    {
        return $universityInfoDataTable->render('university_infos.index');
    }

    /**
     * Show the form for creating a new university_info.
     *
     * @return Response
     */
    public function create()
    {
        $categories = country_universities::orderBy('id')->pluck('university_name', 'id');
        $data = $categories->toArray();

        return view('university_infos.create')->with('university', $data);
    }

    /**
     * Store a newly created university_info in storage.
     *
     * @param Createuniversity_infoRequest $request
     *
     * @return Response
     */
    public function store(Createuniversity_infoRequest $request)
    {
        $input = $request->all();

        $universityInfo = $this->universityInfoRepository->create($input);

        Flash::success('University Info saved successfully.');

        return redirect(route('universityInfos.index'));
    }

    /**
     * Display the specified university_info.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $universityInfo = $this->universityInfoRepository->find($id);

        if (empty($universityInfo)) {
            Flash::error('University Info not found');

            return redirect(route('universityInfos.index'));
        }

        return view('university_infos.show')->with('universityInfo', $universityInfo);
    }

    /**
     * Show the form for editing the specified university_info.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $universityInfo = $this->universityInfoRepository->find($id);

        if (empty($universityInfo)) {
            Flash::error('University Info not found');

            return redirect(route('universityInfos.index'));
        }

        $categories = country_universities::orderBy('id')->pluck('university_name', 'id');
        $data = $categories->toArray();

        return view('university_infos.edit')->with(array('university' => $data, 'universityInfo' => $universityInfo));
    }

    /**
     * Update the specified university_info in storage.
     *
     * @param  int              $id
     * @param Updateuniversity_infoRequest $request
     *
     * @return Response
     */
    public function update($id, Updateuniversity_infoRequest $request)
    {
        $universityInfo = $this->universityInfoRepository->find($id);

        if (empty($universityInfo)) {
            Flash::error('University Info not found');

            return redirect(route('universityInfos.index'));
        }

        $universityInfo = $this->universityInfoRepository->update($request->all(), $id);

        Flash::success('University Info updated successfully.');

        return redirect(route('universityInfos.index'));
    }

    /**
     * Remove the specified university_info from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $universityInfo = $this->universityInfoRepository->find($id);

        if (empty($universityInfo)) {
            Flash::error('University Info not found');

            return redirect(route('universityInfos.index'));
        }

        $this->universityInfoRepository->delete($id);

        Flash::success('University Info deleted successfully.');

        return redirect(route('universityInfos.index'));
    }
}

medical_back/resources/views/university_infos/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            University Info
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'universityInfos.store']) !!}

                        @include('university_infos.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

medical_back/resources/views/university_infos/datatables_actions.blade.php
{!! Form::open(['route' => ['universityInfos.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('universityInfos.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('universityInfos.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

medical_back/resources/views/university_infos/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            University Info
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($universityInfo, ['route' => ['universityInfos.update', $universityInfo->id], 'method' => 'patch']) !!}

                        @include('university_infos.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

medical_back/resources/views/university_infos/fields.blade.php
<!-- University Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('university_id', 'University:') !!}
    {!! Form::select('university_id', $university , null, ['class' => 'form-control']) !!}
</div>

<!-- University Info Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('university_info', 'University Info:') !!}
    {!! Form::textarea('university_info', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('universityInfos.index') }}" class="btn btn-default">Cancel</a>
</div>

medical_back/resources/views/university_infos/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">University Infos</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('universityInfos.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('university_infos.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

medical_back/resources/views/university_infos/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            University Info
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('university_infos.show_fields')
                    <a href="{{ route('universityInfos.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

medical_back/resources/views/university_infos/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $universityInfo->id }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $universityInfo->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $universityInfo->updated_at }}</p>
</div>

<!-- University Id Field -->
<div class="form-group">
    {!! Form::label('university_id', 'University Id:') !!}
    <p>{{ $universityInfo->university_id }}</p>
</div>

<!-- University Info Field -->
<div class="form-group">
    {!! Form::label('university_info', 'University Info:') !!}
    <p>{{ $universityInfo->university_info }}</p>
</div>

medical_back/resources/views/university_infos/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection