medical_back/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');


Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');

Route::resource('countryNames', 'country_nameController');

Route::resource('countryUniversities', 'country_universitiesController');

Route::resource('universityInfos', 'university_infoController');

Route::resource('universityImages', 'university_imagesController');

Route::resource('banners', 'bannerController');

Route::resource('logos', 'logoController');













Route::resource('abouts', 'aboutController');

medical_back/app/Models/country_name.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * @SWG\Definition(
 *      definition="country_name",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="country",
 *          description="country",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="image",
 *          description="image",
 *          type="string"
 *      )
 * )
 */
class country_name extends Model
{

    public $table = 'country_name';
    



    public $fillable = [
        'country',
        'image'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'country' => 'string',
        'image' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

medical_back/app/Http/Controllers/country_nameController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\country_nameDataTable;
use App\Http\Requests;
use App\Http\Requests\Createcountry_nameRequest;
use App\Http\Requests\Updatecountry_nameRequest;
use App\Repositories\country_nameRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class country_nameController extends AppBaseController
{
    /** @var  country_nameRepository */
    private $countryNameRepository;

    public function __construct(country_nameRepository $countryNameRepo)
    {
        $this->countryNameRepository = $countryNameRepo;
    }

    /**
     * Display a listing of the country_name.
     *
     * @param country_nameDataTable $countryNameDataTable
     * @return Response
     */
    public function index(country_nameDataTable $countryNameDataTable)
    {
        return $countryNameDataTable->render('country_names.index');
    }

    /**
     * Show the form for creating a new country_name.
     *
     * @return Response
     */
    public function create()
    {
        return view('country_names.create');
    }

    /**
     * Store a newly created country_name in storage.
     *
     * @param Createcountry_nameRequest $request
     *
     * @return Response
     */
    public function store(Createcountry_nameRequest $request)
    {
        $input = $request->all();

        $file=$request->file('image');
        $filename= $file->getClientOriginalName();
        $filename = str_replace(' ', '_', $filename);
        $file->move(public_path('uploads/countries'), $filename);
        $input['image'] = $filename;

        $countryName = $this->countryNameRepository->create($input);

        Flash::success('Country Name saved successfully.');

        return redirect(route('countryNames.index'));
    }

    /**
     * Display the specified country_name.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $countryName = $this->countryNameRepository->find($id);

        if (empty($countryName)) {
            Flash::error('Country Name not found');

            return redirect(route('countryNames.index'));
        }

        return view('country_names.show')->with('countryName', $countryName);
    }

    /**
     * Show the form for editing the specified country_name.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $countryName = $this->countryNameRepository->find($id);

        if (empty($countryName)) {
            Flash::error('Country Name not found');

            return redirect(route('countryNames.index'));
        }

        return view('country_names.edit')->with('countryName', $countryName);
    }

    /**
     * Update the specified country_name in storage.
     *
     * @param  int              $id
     * @param Updatecountry_nameRequest $request
     *
     * @return Response
     */
    public function update($id, Updatecountry_nameRequest $request)
    {
        $countryName = $this->countryNameRepository->find($id);

        if (empty($countryName)) {
            Flash::error('Country Name not found');

            return redirect(route('countryNames.index'));
        }

        $input = $request->all();

        $file=$request->file('image');
        if($file) {
            $filename= $file->getClientOriginalName();
            $filename = str_replace(' ', '_', $filename);
            $file->move(public_path('uploads/countries'), $filename);
            $input['image'] = $filename;    
        }

        $countryName = $this->countryNameRepository->update($input, $id);

        Flash::success('Country Name updated successfully.');

        return redirect(route('countryNames.index'));
    }

    /**
     * Remove the specified country_name from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $countryName = $this->countryNameRepository->find($id);

        if (empty($countryName)) {
            Flash::error('Country Name not found');

            return redirect(route('countryNames.index'));
        }

        $this->countryNameRepository->delete($id);

        Flash::success('Country Name deleted successfully.');

        return redirect(route('countryNames.index'));
    }
}

medical_back/resources/views/country_names/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Country Name
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'countryNames.store', 'files' => true]) !!}

                        @include('country_names.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

medical_back/resources/views/country_names/datatables_actions.blade.php
{!! Form::open(['route' => ['countryNames.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('countryNames.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('countryNames.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

medical_back/resources/views/country_names/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Country Name
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($countryName, ['route' => ['countryNames.update', $countryName->id], 'method' => 'patch', 'files' => true]) !!}

                        @include('country_names.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

medical_back/resources/views/country_names/fields.blade.php
<!-- Country Field -->
<div class="form-group col-sm-6">
    {!! Form::label('country', 'Country:') !!}
    {!! Form::text('country', null, ['class' => 'form-control']) !!}
</div>

<!-- Image Field -->
<div class="form-group col-sm-6">
    {!! Form::label('image', 'Image:') !!}
    {!! Form::file('image') !!}
</div>
<div class="clearfix"></div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('countryNames.index') }}" class="btn btn-default">Cancel</a>
</div>

medical_back/resources/views/country_names/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Country Names</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('countryNames.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('country_names.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

medical_back/resources/views/country_names/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Country Name
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('country_names.show_fields')
                    <a href="{{ route('countryNames.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

medical_back/resources/views/country_names/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $countryName->id }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $countryName->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $countryName->updated_at }}</p>
</div>

<!-- Country Field -->
<div class="form-group">
    {!! Form::label('country', 'Country:') !!}
    <p>{{ $countryName->country }}</p>
</div>

<!-- Image Field -->
<div class="form-group">
    {!! Form::label('image', 'Image:') !!}
    <p>{{ $countryName->image }}</p>
</div>

medical_back/resources/views/country_names/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection