medical_back/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');


Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');

Route::resource('countryNames', 'country_nameController');

Route::resource('countryUniversities', 'country_universitiesController');

Route::resource('universityInfos', 'university_infoController');

Route::resource('universityImages', 'university_imagesController');

Route::resource('banners', 'bannerController');

Route::resource('logos', 'logoController');













Route::resource('abouts', 'aboutController');

medical_back/app/Http/Controllers/country_universitiesController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\country_universitiesDataTable;
use App\Http\Requests;
use App\Models\country_name;
use App\Http\Requests\Createcountry_universitiesRequest;
use App\Http\Requests\Updatecountry_universitiesRequest;
use App\Repositories\country_universitiesRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class country_universitiesController extends AppBaseController
{
    /** @var  country_universitiesRepository */
    private $countryUniversitiesRepository;

    public function __construct(country_universitiesRepository $countryUniversitiesRepo)
    {
        $this->countryUniversitiesRepository = $countryUniversitiesRepo;
    }

    /**
     * Display a listing of the country_universities.
     *
     * @param country_universitiesDataTable $countryUniversitiesDataTable
     * @return Response
     */
    public function index(country_universitiesDataTable $countryUniversitiesDataTable)
    {
        return $countryUniversitiesDataTable->render('country_universities.index');
    }

    /**
     * Show the form for creating a new country_universities.
     *
     * @return Response
     */
    public function create()
    {
        $categories = country_name::orderBy('id')->pluck('country', 'id');
        $data = $categories->toArray();

        return view('country_universities.create')->with('country', $data);
//        return view('country_universities.create');
    }

    /**
     * Store a newly created country_universities in storage.
     *
     * @param Createcountry_universitiesRequest $request
     *
     * @return Response
     */
    public function store(Createcountry_universitiesRequest $request)
    {
        $input = $request->all();

        $file=$request->file('university_images');
        $filename= $file->getClientOriginalName();
        $filename = str_replace(' ', '_', $filename);
        $file->move(public_path('uploads/country_university'), $filename);
        $input['university_images'] = $filename;

        $countryUniversities = $this->countryUniversitiesRepository->create($input);

        Flash::success('Country Universities saved successfully.');

        return redirect(route('countryUniversities.index'));
    }

    /**
     * Display the specified country_universities.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $countryUniversities = $this->countryUniversitiesRepository->find($id);

        if (empty($countryUniversities)) {
            Flash::error('Country Universities not found');

            return redirect(route('countryUniversities.index'));
        }

        return view('country_universities.show')->with('countryUniversities', $countryUniversities);
    }

    /**
     * Show the form for editing the specified country_universities.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $countryUniversities = $this->countryUniversitiesRepository->find($id);

        if (empty($countryUniversities)) {
            Flash::error('Country Universities not found');

            return redirect(route('countryUniversities.index'));
        }

        return view('country_universities.edit')->with('countryUniversities', $countryUniversities);
    }

    /**
     * Update the specified country_universities in storage.
     *
     * @param  int              $id
     * @param Updatecountry_universitiesRequest $request
     *
     * @return Response
     */
    public function update($id, Updatecountry_universitiesRequest $request)
    {
        $countryUniversities = $this->countryUniversitiesRepository->find($id);

        if (empty($countryUniversities)) {
            Flash::error('Country Universities not found');

            return redirect(route('countryUniversities.index'));
        }

        $input = $request->all();

        $file=$request->file('university_images');
        if($file) {
            $filename= $file->getClientOriginalName();
            $filename = str_replace(' ', '_', $filename);
            $file->move(public_path('uploads/country_university'), $filename);
            $input['university_images'] = $filename;    
        }

        $countryUniversities = $this->countryUniversitiesRepository->update($input, $id);

        Flash::success('Country Universities updated successfully.');

        return redirect(route('countryUniversities.index'));
    }

    /**
     * Remove the specified country_universities from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $countryUniversities = $this->countryUniversitiesRepository->find($id);

        if (empty($countryUniversities)) {
            Flash::error('Country Universities not found');

            return redirect(route('countryUniversities.index'));
        }

        $this->countryUniversitiesRepository->delete($id);

        Flash::success('Country Universities deleted successfully.');

        return redirect(route('countryUniversities.index'));
    }
}

medical_back/resources/views/country_universities/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Country Universities
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'countryUniversities.store', 'files' => true]) !!}

                        @include('country_universities.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

medical_back/resources/views/country_universities/datatables_actions.blade.php
{!! Form::open(['route' => ['countryUniversities.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('countryUniversities.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('countryUniversities.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

medical_back/resources/views/country_universities/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Country Universities
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($countryUniversities, ['route' => ['countryUniversities.update', $countryUniversities->id], 'method' => 'patch', 'files' => true]) !!}

                        @include('country_universities.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

medical_back/resources/views/country_universities/fields.blade.php
<!-- Country Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('country_id', 'Country:') !!}
    {!! Form::select('country_id', $country , null, ['class' => 'form-control']) !!}
</div>

<!-- University Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('university_name', 'University Name:') !!}
    {!! Form::text('university_name', null, ['class' => 'form-control']) !!}
</div>

<!-- University Images Field -->
<div class="form-group col-sm-6">
    {!! Form::label('university_images', 'University Images:') !!}
    {!! Form::file('university_images') !!}
</div>
<div class="clearfix"></div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('countryUniversities.index') }}" class="btn btn-default">Cancel</a>
</div>

medical_back/resources/views/country_universities/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Country Universities</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('countryUniversities.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('country_universities.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

medical_back/resources/views/country_universities/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Country Universities
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('country_universities.show_fields')
                    <a href="{{ route('countryUniversities.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

medical_back/resources/views/country_universities/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $countryUniversities->id }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $countryUniversities->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $countryUniversities->updated_at }}</p>
</div>

<!-- Country Id Field -->
<div class="form-group">
    {!! Form::label('country_id', 'Country Id:') !!}
    <p>{{ $countryUniversities->country_id }}</p>
</div>

<!-- University Name Field -->
<div class="form-group">
    {!! Form::label('university_name', 'University Name:') !!}
    <p>{{ $countryUniversities->university_name }}</p>
</div>

<!-- University Images Field -->
<div class="form-group">
    {!! Form::label('university_images', 'University Images:') !!}
    <p>{{ $countryUniversities->university_images }}</p>
</div>

medical_back/resources/views/country_universities/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection